domain: keptintheway.org
url: https://keptintheway.org
baseurl: ""
theme: minima
title: "Kept in the Way Blog"
description: "A blog of encouragement for Christians seeking to be kept in the Way of Jesus"